from __future__ import annotations

FULL_PACKAGE_SET_DEBIAN: list[str] = [
    "manpages",
    "manpages-dev",
    "bash",
    "coreutils",
    "util-linux",
    "findutils",
    "grep",
    "sed",
    "gawk",
    "curl",
    "wget",
    "openssh-client",
    "rsync",
    "netcat-openbsd",
    "systemd",
    "vim",
    "less",
    "git",
    "make",
    "gcc",
    "gdb",
    "nginx",
    "apache2",
    "openssl",
    "libssl-dev",
    "python3",
    "perl",
    "iproute2",
    "procps",
    "postgresql-client",
    "default-mysql-client",
]

FULL_PACKAGE_SET_UBUNTU: list[str] = FULL_PACKAGE_SET_DEBIAN

FULL_PACKAGE_SET_FEDORA: list[str] = [
    "man-pages",
    "bash",
    "coreutils",
    "util-linux",
    "findutils",
    "grep",
    "sed",
    "gawk",
    "curl",
    "wget",
    "openssh-clients",
    "rsync",
    "systemd",
    "vim-enhanced",
    "less",
    "git",
    "make",
    "gcc",
    "gdb",
    "nginx",
    "httpd",
    "openssl",
    "openssl-devel",
    "python3",
    "perl",
    "iproute",
    "procps-ng",
    "postgresql",
]

FULL_PACKAGE_SET_ARCH: list[str] = [
    "man-pages",
    "bash",
    "coreutils",
    "util-linux",
    "findutils",
    "grep",
    "sed",
    "gawk",
    "curl",
    "wget",
    "openssh",
    "rsync",
    "openbsd-netcat",
    "systemd",
    "vim",
    "less",
    "git",
    "make",
    "gcc",
    "gdb",
    "nginx",
    "apache",
    "openssl",
    "python",
    "perl",
    "iproute2",
    "procps-ng",
]

FULL_PACKAGE_SET_ALPINE: list[str] = [
    "man-pages",
    "busybox-doc",
    "bash",
    "coreutils",
    "util-linux",
    "findutils",
    "grep",
    "sed",
    "gawk",
    "curl",
    "wget",
    "openssh-client",
    "rsync",
    "less",
    "git",
    "make",
    "gcc",
    "gdb",
    "nginx",
    "apache2",
    "openssl",
    "python3",
    "perl",
    "iproute2",
    "procps",
]

FULL_PACKAGE_SET_BY_DISTRO: dict[str, list[str]] = {
    "debian": FULL_PACKAGE_SET_DEBIAN,
    "ubuntu": FULL_PACKAGE_SET_UBUNTU,
    "fedora": FULL_PACKAGE_SET_FEDORA,
    "arch": FULL_PACKAGE_SET_ARCH,
    "alpine": FULL_PACKAGE_SET_ALPINE,
}

FULL_PACKAGE_SET: list[str] = FULL_PACKAGE_SET_DEBIAN
