from __future__ import annotations

FULL_PACKAGE_SET: list[str] = [
    "manpages",
    "manpages-dev",
    "bash",
    "coreutils",
    "util-linux",
    "findutils",
    "grep",
    "sed",
    "gawk",
    "curl",
    "wget",
    "openssh-client",
    "rsync",
    "netcat-openbsd",
    "systemd",
    "vim",
    "less",
    "git",
    "make",
    "gcc",
    "gdb",
    "nginx",
    "apache2",
    "openssl",
    "libssl-dev",
    "python3",
    "perl",
    "iproute2",
    "procps",
    "postgresql-client",
    "default-mysql-client",
]
