/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Info */
        get: operations["get_info_api_v1_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/licenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Licenses */
        get: operations["list_licenses_api_v1_licenses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/licenses/{package}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get License */
        get: operations["get_license_api_v1_licenses__package__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/man/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Man By Name */
        get: operations["get_man_by_name_api_v1_man__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/man/{name}/{section}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Man By Name And Section */
        get: operations["get_man_by_name_and_section_api_v1_man__name___section__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/man/{name}/{section}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Related */
        get: operations["get_related_api_v1_man__name___section__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/section/{section}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Section */
        get: operations["list_section_api_v1_section__section__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sections */
        get: operations["list_sections_api_v1_sections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggest */
        get: operations["suggest_api_v1_suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AmbiguousOption */
        AmbiguousOption: {
            /** Description */
            description: string;
            /** Section */
            section: string;
            /** Title */
            title: string;
        };
        /** AmbiguousPageResponse */
        AmbiguousPageResponse: {
            error: components["schemas"]["ErrorDetail"];
            /** Options */
            options: components["schemas"]["AmbiguousOption"][];
        };
        /** BlockNode */
        BlockNode: components["schemas"]["HeadingBlock"] | components["schemas"]["ParagraphBlock"] | components["schemas"]["ListBlock"] | components["schemas"]["DefinitionListBlock"] | components["schemas"]["CodeBlock"] | components["schemas"]["TableBlock"] | components["schemas"]["HorizontalRuleBlock"];
        /** CodeBlock */
        CodeBlock: {
            /** Id */
            id?: string | null;
            /** Languagehint */
            languageHint?: string | null;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "code_block";
        };
        /** CodeInline */
        CodeInline: {
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "code";
        };
        /** DefinitionListBlock */
        DefinitionListBlock: {
            /** Items */
            items: components["schemas"]["DefinitionListItem"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "definition_list";
        };
        /** DefinitionListItem */
        DefinitionListItem: {
            /** Definitionblocks */
            definitionBlocks: components["schemas"]["BlockNode"][];
            /** Id */
            id?: string | null;
            /** Terminlines */
            termInlines: components["schemas"]["InlineNode"][];
        };
        /** EmphasisInline */
        EmphasisInline: {
            /** Inlines */
            inlines: components["schemas"]["InlineNode"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "emphasis";
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeadingBlock */
        HeadingBlock: {
            /** Id */
            id: string;
            /** Level */
            level: number;
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "heading";
        };
        /** HorizontalRuleBlock */
        HorizontalRuleBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "horizontal_rule";
        };
        /** InfoResponse */
        InfoResponse: {
            /** Datasetreleaseid */
            datasetReleaseId: string;
            /** Distro */
            distro: string;
            /** Lastupdated */
            lastUpdated: string;
            /** Locale */
            locale: string;
            /** Pagecount */
            pageCount: number;
        };
        /** InlineNode */
        InlineNode: components["schemas"]["TextInline"] | components["schemas"]["CodeInline"] | components["schemas"]["EmphasisInline"] | components["schemas"]["StrongInline"] | components["schemas"]["LinkInline"];
        /** LicensePackage */
        LicensePackage: {
            /** Haslicensetext */
            hasLicenseText: boolean;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** LicenseTextResponse */
        LicenseTextResponse: {
            /** Licenseid */
            licenseId: string;
            /** Licensename */
            licenseName: string;
            /** Package */
            package: string;
            /** Text */
            text: string;
        };
        /** LicensesResponse */
        LicensesResponse: {
            /** Datasetreleaseid */
            datasetReleaseId: string;
            /** Imagedigest */
            imageDigest: string;
            /** Imageref */
            imageRef: string;
            /** Ingestedat */
            ingestedAt: string;
            /** Packagemanifest */
            packageManifest: {
                [key: string]: unknown;
            } | null;
            /** Packages */
            packages: components["schemas"]["LicensePackage"][];
        };
        /** LinkInline */
        LinkInline: {
            /** Href */
            href: string;
            /** Inlines */
            inlines: components["schemas"]["InlineNode"][];
            /**
             * Linktype
             * @enum {string}
             */
            linkType: "internal" | "external" | "unresolved";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "link";
        };
        /** ListBlock */
        ListBlock: {
            /** Items */
            items: components["schemas"]["BlockNode"][][];
            /** Ordered */
            ordered: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "list";
        };
        /** ManPage */
        ManPage: {
            /** Datasetreleaseid */
            datasetReleaseId: string;
            /** Description */
            description: string;
            /** Distro */
            distro: string;
            /** Id */
            id: string;
            /** Locale */
            locale: string;
            /** Name */
            name: string;
            /** Section */
            section: string;
            /** Sourcepackage */
            sourcePackage?: string | null;
            /** Sourcepackageversion */
            sourcePackageVersion?: string | null;
            /** Title */
            title: string;
        };
        /** ManPageContent */
        ManPageContent: {
            /** Blocks */
            blocks: components["schemas"]["BlockNode"][];
            /** Options */
            options?: components["schemas"]["OptionItem"][] | null;
            /** Seealso */
            seeAlso?: components["schemas"]["SeeAlsoRef"][] | null;
            /** Synopsis */
            synopsis?: string[] | null;
            /** Toc */
            toc: components["schemas"]["TocItem"][];
        };
        /** ManPageResponse */
        ManPageResponse: {
            content: components["schemas"]["ManPageContent"];
            page: components["schemas"]["ManPage"];
            /** Variants */
            variants: components["schemas"]["ManPageVariant"][];
        };
        /** ManPageVariant */
        ManPageVariant: {
            /** Contentsha256 */
            contentSha256: string;
            /** Datasetreleaseid */
            datasetReleaseId: string;
            /** Distro */
            distro: string;
        };
        /** OptionItem */
        OptionItem: {
            /** Anchorid */
            anchorId: string;
            /** Argument */
            argument?: string | null;
            /** Description */
            description: string;
            /** Flags */
            flags: string;
        };
        /** ParagraphBlock */
        ParagraphBlock: {
            /** Inlines */
            inlines: components["schemas"]["InlineNode"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "paragraph";
        };
        /** RelatedResponse */
        RelatedResponse: {
            /** Items */
            items: components["schemas"]["SectionPage"][];
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchResult"][];
            /** Suggestions */
            suggestions: string[];
        };
        /** SearchResult */
        SearchResult: {
            /** Description */
            description: string;
            /** Highlights */
            highlights: string[];
            /** Name */
            name: string;
            /** Section */
            section: string;
            /** Title */
            title: string;
        };
        /** SectionLabel */
        SectionLabel: {
            /** Label */
            label: string;
            /** Section */
            section: string;
        };
        /** SectionPage */
        SectionPage: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Section */
            section: string;
            /** Title */
            title: string;
        };
        /** SectionResponse */
        SectionResponse: {
            /** Label */
            label: string;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Results */
            results: components["schemas"]["SectionPage"][];
            /** Section */
            section: string;
            /** Total */
            total: number;
        };
        /** SeeAlsoRef */
        SeeAlsoRef: {
            /** Name */
            name: string;
            /** Resolvedpageid */
            resolvedPageId?: string | null;
            /** Section */
            section?: string | null;
        };
        /** StrongInline */
        StrongInline: {
            /** Inlines */
            inlines: components["schemas"]["InlineNode"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "strong";
        };
        /** SuggestResponse */
        SuggestResponse: {
            /** Query */
            query: string;
            /** Suggestions */
            suggestions: components["schemas"]["Suggestion"][];
        };
        /** Suggestion */
        Suggestion: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Section */
            section: string;
        };
        /** TableBlock */
        TableBlock: {
            /** Headers */
            headers: string[];
            /** Rows */
            rows: string[][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "table";
        };
        /** TextInline */
        TextInline: {
            /** Text */
            text: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        };
        /** TocItem */
        TocItem: {
            /** Id */
            id: string;
            /** Level */
            level: number;
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_info_api_v1_info_get: {
        parameters: {
            query?: {
                distro?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_licenses_api_v1_licenses_get: {
        parameters: {
            query?: {
                distro?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LicensesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_license_api_v1_licenses__package__get: {
        parameters: {
            query?: {
                distro?: string | null;
            };
            header?: never;
            path: {
                package: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LicenseTextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_man_by_name_api_v1_man__name__get: {
        parameters: {
            query?: {
                distro?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManPageResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AmbiguousPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_man_by_name_and_section_api_v1_man__name___section__get: {
        parameters: {
            query?: {
                distro?: string | null;
            };
            header?: never;
            path: {
                name: string;
                section: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_related_api_v1_man__name___section__related_get: {
        parameters: {
            query?: {
                distro?: string | null;
            };
            header?: never;
            path: {
                name: string;
                section: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
                section?: string | null;
                limit?: number;
                offset?: number;
                distro?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_section_api_v1_section__section__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                distro?: string | null;
            };
            header?: never;
            path: {
                section: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sections_api_v1_sections_get: {
        parameters: {
            query?: {
                distro?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionLabel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_api_v1_suggest_get: {
        parameters: {
            query: {
                name: string;
                distro?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
}
