services:
  - type: web
    name: betterman-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CORS_ORIGINS
        value: "https://betterman.sh,https://www.betterman.sh,http://localhost:5173"