name: betterman-api
region: nyc

services:
  - name: api
    github:
      repo: amanthanvi/BetterMan
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile.appplatform
    
    # Environment
    envs:
      - key: DATABASE_PATH
        value: /data/betterman.db
      - key: ADMIN_TOKEN
        type: SECRET
        value: ${ADMIN_TOKEN}
      - key: SPACES_ACCESS_KEY
        type: SECRET
        value: ${SPACES_ACCESS_KEY}
      - key: SPACES_SECRET_KEY
        type: SECRET
        value: ${SPACES_SECRET_KEY}
      - key: SPACES_BUCKET_NAME
        value: betterman-backups
      - key: SPACES_REGION
        value: nyc3
      - key: REDIS_URL
        value: redis://localhost:6379
      - key: ENVIRONMENT
        value: production
    
    # HTTP configuration
    http_port: 8000
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Resources
    instance_count: 1
    instance_size_slug: basic-xxs  # 512 MB RAM, 1 vCPU, $5/month
    
    # Persistent storage for SQLite
    # Note: App Platform doesn't support persistent volumes yet
    # We'll use Spaces for persistence instead

jobs:
  - name: parse-man-pages
    kind: PRE_DEPLOY
    github:
      repo: amanthanvi/BetterMan
      branch: main
    source_dir: backend
    dockerfile_path: backend/Dockerfile.appplatform
    run_command: python scripts/parse_man_pages_to_sqlite.py
    
  - name: backup-database
    kind: WORKER
    github:
      repo: amanthanvi/BetterMan
      branch: main
    source_dir: backend
    dockerfile_path: backend/Dockerfile.appplatform
    run_command: python scripts/backup_to_spaces.py
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_PATH
        value: /data/betterman.db
      - key: SPACES_ACCESS_KEY
        type: SECRET
        value: ${SPACES_ACCESS_KEY}
      - key: SPACES_SECRET_KEY
        type: SECRET
        value: ${SPACES_SECRET_KEY}