name: Bug report
description: Something isn't working
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen, and what happened instead?
      placeholder: Tell us what you see.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: A minimal set of steps so we can reproduce the problem.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Tag, commit SHA, or deployment URL.
      placeholder: e.g. v0.1.0, 58f7a24, https://...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste any relevant logs, console output, or screenshots.
      render: shell
    validations:
      required: false
