#!/bin/bash

echo "🚀 BetterMan Deployment Setup Helper"
echo "===================================="
echo ""

# Generate admin token
echo "📝 Generating secure admin token..."
ADMIN_TOKEN=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")
echo "ADMIN_TOKEN=$ADMIN_TOKEN"
echo ""

echo "🔧 Next Steps:"
echo ""
echo "1. Vercel Token:"
echo "   - Go to: https://vercel.com/account/tokens"
echo "   - Create new token with 'Full Account' scope"
echo "   - Add to GitHub Secrets as VERCEL_TOKEN"
echo ""
echo "2. Render Setup:"
echo "   - Create PostgreSQL database (or use SQLite)"
echo "   - Create Redis instance"
echo "   - Create Web Service for backend"
echo "   - Get API Key from: https://dashboard.render.com/settings/api-keys"
echo "   - Get Service ID from your service URL"
echo ""
echo "3. GitHub Secrets to add:"
echo "   - VERCEL_TOKEN"
echo "   - RENDER_API_KEY"
echo "   - RENDER_SERVICE_ID"
echo ""
echo "4. Render Environment Variables:"
echo "   DATABASE_URL=sqlite:///./data/betterman.db"
echo "   REDIS_URL=<your-redis-internal-url>"
echo "   ADMIN_TOKEN=$ADMIN_TOKEN"
echo "   BACKEND_CORS_ORIGINS=[\"https://your-app.vercel.app\",\"http://localhost:3000\"]"
echo ""
echo "📌 Save this admin token securely!"